export enum PaymentType {
  TIP_PURCHASE = "TIP_PURCHASE",
  ESCROW_REFUND = "ESCROW_REFUND",
  TIPSTER_PAYOUT = "TIPSTER_PAYOUT",
  PLATFORM_REVENUE = "PLATFORM_REVENUE",
  WITHDRAWAL = "WITHDRAWAL",
  DEPOSIT = "DEPOSIT",
  FEE = "FEE",
  OTHER = "OTHER",
}
