export enum ReportType {
  TIPSTER_MISCONDUCT = "TIPSTER_MISCONDUCT",
  FRAUD = "FRAUD",
  INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT",
  PAYMENT_ISSUE = "PAYMENT_ISSUE",
  TECHNICAL_ISSUE = "TECHNICAL_ISSUE",
  OTHER = "OTHER",
}
