export enum TransactionType {
  PURCHASE = "PURCHASE",
  TIPSTER_PAYOUT = "TIPSTER_PAYOUT",
  CUSTOMER_REFUND = "CUSTOMER_REFUND",
  PLATFORM_REVENUE = "PLATFORM_REVENUE",
  WITHDRAWAL = "WITHDRAWAL",
  DEPOSIT = "DEPOSIT",
  FEE = "FEE",
}
